<?php
// Database connection constants
define("DATABASE_HOST", "ENTER YOUR DB HOSTNAME");
define("DATABASE_USERNAME", "ENTER YOUR USERNAME");
define("DATABASE_PASSWORD", "ENTER YOUR PASSWORD");
define("DATABASE_NAME", "ENTER YOUR DB NAME");
?>
